main: com.amansprojects.moonphase.ffa.Main
name: CitrusFFA
version: 3.2
author: ninjadev64 (IGN ninjagamer64)
description: Free For All
commands: 
   ffa:
      description: Join the FFA infinite minigame.
      usage: /ffa