main: com.amansprojects.citrusdev.ffa.Main
name: CitrusFFA
softdepend: [Vault, PlaceholderAPI]
version: 3.3
author: ninjadev64 (IGN ninjagamer64)
description: Free For All
commands: 
   ffa:
      description: Join the FFA infinite minigame.
      usage: /ffa